["fzf-completion.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh"
  refresh = 0 # only refresh manually

["fzf-key-bindings.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh"
  refresh = 0 # only refresh manually

