[".zprezto"]
  type = "git-repo"
  url = "https://github.com/sorin-ionescu/prezto.git"
  clone.args = ["--depth=100",
    "--shallow-submodules",
    "--recurse-submodules=modules/completion/external",
    "--recurse-submodules=modules/prompt/*",
  ]
  pull.args = ["--recurse-submodules"]
  refreshPeriod = "720h" # every 30 days

