[tools]
"github:smol-machines/smolvm" = { version = "0.5.19" }
tmux = "latest"
neovim = "latest"
claude = "latest"
atuin = "18.12.1"
github-cli = "2.87.3"
uv = "latest"
ente = "cli-v0.2.3"

[tool_alias]
ente = "github:ente-io/ente"

