{{ $direnvVersion := "2.32.3" }}
{{ $fxVersion := "30.0.3" }}
{{ $sopsVersion := "3.7.3" }}
{{ $yqVersion := "4.25.1" }}

["direnv"]
  type = "file"
  url = "https://github.com/direnv/direnv/releases/download/v{{ $direnvVersion }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true

["fasd"]
  type = "file"
  url = "https://raw.githubusercontent.com/clvv/fasd/master/fasd"
  executable = true

["fx"]
  type = "file"
  url = "https://github.com/antonmedv/fx/releases/download/30.0.3/fx_{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
  executable = true

["gimme"]
  type = "file"
  url = "https://raw.githubusercontent.com/travis-ci/gimme/master/gimme"
  executable = true

["fzf-tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux"
  executable = true
  refresh = 0 # only manually

["mise"]
  type = "file"
  {{ $miseSuffix := printf "%v-%v" .chezmoi.os .chezmoi.arch }}
  {{ $miseSuffix = $miseSuffix | replace "darwin" "macos" | replace "amd64" "x64" }}
  url = "https://mise.jdx.dev/mise-latest-{{ $miseSuffix }}"
  executable = true

["sops"]
  type = "file"
  url = "https://github.com/mozilla/sops/releases/download/v{{ $sopsVersion }}/sops-v{{ $sopsVersion }}.{{ .chezmoi.os }}.{{ .chezmoi.arch }}"
  executable = true

["yq"]
  type = "file"
  url = "https://github.com/mikefarah/yq/releases/download/v{{ $yqVersion }}/yq_{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
  executable = true
  refresh = 0
