["fasd"]
  type = "file"
  url = "https://raw.githubusercontent.com/clvv/fasd/master/fasd"
  executable = true

["gimme"]
  type = "file"
  url = "https://raw.githubusercontent.com/travis-ci/gimme/master/gimme"
  executable = true

["fzf-tmux"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux"
  executable = true
  refresh = 0 # only manually

