{{ $ageVersion := "1.0.0" }}
{{ $fzfVersion := "0.30.0" }}
{{ $tmuxFastCopyVersion := "0.8.0" }}

["age"]
  type = "archive"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"

["fzf"]
  type = "archive"

  ## fzf uses .zip for Windows/Darwin, and .tar.gz for others.
  {{ $fzfReleaseExt := "tar.gz" }}
  {{ if eq .chezmoi.os "darwin" }}
  {{ $fzfReleaseExt = "zip" }}
  {{ end }}
  url = "https://github.com/junegunn/fzf/releases/download/{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.{{ $fzfReleaseExt }}"

["tmux-fastcopy"]
  type = "archive"

  ## tmux-fastcopy uses x86_64 instead of amd64
  {{ $tmuxFastCopyArch := .chezmoi.arch | replace "amd64" "x86_64" }}
  url = "https://github.com/abhinav/tmux-fastcopy/releases/download/v{{ $tmuxFastCopyVersion }}/tmux-fastcopy_{{ $tmuxFastCopyVersion }}_{{ .chezmoi.os }}_{{ $tmuxFastCopyArch }}.tar.gz"